name: Freeze Verify
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  verify:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check freeze artifacts exist
        shell: pwsh
        run: |
          ls discover/out/discoveries.md, discover/out/freeze.json, discover/out/freeze.sha256, claims.ndjson | Format-Table
      - name: Verify freeze hash
        shell: pwsh
        run: |
          $rec = (Get-Content discover/out/freeze.sha256).Split(' ')[0]
          $act = (Get-FileHash discover/out/freeze.json -Algorithm SHA256).Hash.ToLower()
          if ($rec -ne $act) { Write-Error "freeze mismatch: recorded=$rec actual=$act"; exit 1 }
          "freeze ok: $rec"
